config/routes.rb
BlogR3::Application.routes.draw do

  root to: "articles#index"
  resources :articles, only: ['index', 'create', 'new', 'show'] do
    resources :comments, only: 'create'
  end

end

app/models/article.rb
class Article < Neo4j::Rails::Model
  include ActiveModel::Validations

  property :title, type: String
  property :text_content, type: String
  property :published_at, type: DateTime

  has_n :comments

  validates_presence_of :title
end

app/models/comment.rb
class Comment < Neo4j::Rails::Model
  include ActiveModel::Validations
  property :author, type: String
  property :text_content, type: String

  validates_presence_of :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_filter :initialize_service

  # Actions assigned to routing

  # List of articles
  def index
    @articles = Article.all
  end

  # Show article
  def show
    @article = @article_service.find(params[:id])
    @comment = Comment.new()
  end

  # Form to create new article
  def new
    @article = Article.new()
  end

  # Action to create new article
  def create
    @article_service.create_article(Article.new(params[:article]))
  end

  # Callbacks from service call

  # Callback after article was created
  def article_created(article)
    respond_to do |format|
      format.html { redirect_to root_path}
    end
  end

  # Callback after article was NOT created
  def article_create_error(article)
    @article = article
    respond_to do |format|
      format.html { render 'new' }
    end
  end

  # Callback when article was not found
  def article_not_found(article_id)
    Rails.logger.info("try to show missing article with id: #{article_id}.")
    redirect_to root_path
  end

  private

  def initialize_service
    @article_service = ArticleService.new(self)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_filter :initialize_service

  # Action to create new comment assigned to article
  def create
    comment = Comment.new(params[:comment])
    @articles_comments_service.create_comment(comment)
  end

  # Callbacks from service

  # Callback after comment created successfully
  def comment_created(comment)
    Rails.logger.info("Comment was created")
    @comments = [comment]
    respond_to do |format|
      format.html { redirect_to article_path(@article.id) }
      format.js
    end
  end

  # Callback after comment was NOT created
  def comment_create_error(comment)
    Rails.logger.info("Comment was NOT created")
    @comment = comment
    respond_to do |format|
      format.html { render 'articles/show' }
      format.js { render 'create_error' }
    end

  end

  private

  def initialize_service
    @article = Article.find(params[:article_id])
    if @article.nil?
      redirect_to :root_path
      return false
    end
    @articles_comments_service = ArticleCommentsService.new(@article, self)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/views/articles/index.html.erb
<div class="articles-list">
  <% @articles.each do |article| %>
    <h2><%= link_to(article.title, article_path(article)) %></h2>
    <p><%= article.text_content[0,250] %><%= " ..." if article.text_content.to_s.size > 250 %></p>
    <hr />
  <% end %>
</div>

app/views/articles/new.html.erb
<%= form_for(@article, html: { class: 'form', role: 'form'}) do |f| %>

  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control' %>
    <% if @article.errors[:title].any? %>
      <div class="help-block alert alert-danger"><%= @article.errors[:title].join(". ") %></div>
    <% end %>
  </div>

  <div class="form-group">
    <%= f.label :text_content %>
    <%= f.text_area :text_content, class: 'form-control' %>
  </div>

  <div class="text-right">
    <%= f.submit('Create', class: 'btn btn-success') %>
  </div>
<% end %>

app/views/articles/show.html.erb
<div class="articles article-show">
  <h2>
    <%= @article.title %>
  </h2>

  <div>
    <%= link_to('All articles',articles_path()) %> / <%= link_to(@article.title, article_path()) %>
  </div>

  <p>
    <%= simple_format(@article.text_content) %>
  </p>

  <hr />
  <div class="comments">
    <h3>Comments</h3>
    <%= render partial: 'comments/list_with_form', locals: { comments: @article.comments } %>
  </div>
</div>

app/views/comments/_list.html.erb
<% comments.each do |comment| %>
  <h4><%= comment.author %>:</h4>
  <p>
    <%= simple_format(comment.text_content) %>
  </p>
<% end %>

app/views/comments/_list_with_form.html.erb
<%= form_for(@comment, url: article_comments_path(@article), remote: true,
             html: { role: 'form', class: 'form' }) do |f| %>
  <div class="form-group">
    <%= f.label :author %>
    <%= f.text_field :author, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :text_content, "Comment" %>
    <%= f.text_area :text_content, rows: 3, class: 'form-control' %>
  </div>
  <div class="form-group text-right">
    <%= f.submit('Add comment', class: 'btn btn-success') %>
  </div>
<% end %>

<div class="comments comments-list">
  <%= render partial: 'comments/list', locals: { comments: comments } %>
</div>

app/views/comments/create.js.erb
$("#new_comment")[0].reset();
$(".comments.comments-list").append('<%= escape_javascript(render(partial: 'comments/list', locals: { comments: @comments })) %>');

app/views/comments/create_error.js.erb
alert('<%= (@comment.errors.map{|k,v| v.to_s }.join(".")) %>');

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Blog</title>

  <!-- Bootstrap -->
  <%= stylesheet_link_tag    "application", :media => "all" %>

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
  <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
  <![endif]-->
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container" id="content">
  <div class="col-sm-12">
    <h1>Blog</h1>
  </div>
  <div class="col-sm-10">
    <%= yield %>
  </div>
  <div class="col-sm-2">
    <ul class="nav nav-pills">
      <li><%= link_to("New article", new_article_path) %></li>
    </ul>
  </div>
</div>

<%= javascript_include_tag "application" %>
</body>
</html>